### PR TITLE
SSCINF-1485: Addressed minor errors in python section

### PR DESCRIPTION
**Pull request by josephwhitney-wk**
[SSCINF-1485](https://jira.atl.workiva.net/browse/SSCINF-1485)| Workiva styleguide README.md has minor errors
:-------|:-------
Solution | Update python/style.rst to fix minor errors
Status | Issue Status
Reviewers | @devingray-wf @larrylynn-wf

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
Number of Findings: 0

**Comment by garyorser-wf** [comment]
+1

**Comment by josephwhitney-wk** [comment]
@Workiva/release-management-p

**Comment by chrislococo-wf** [comment]
+1

Hell of a typo!

**Pull request merged**
