### PR TITLE
Rename style.rst to style.md

### PR DESCRIPTION
**Pull request by robertharwell-wf**
Dev portal does not render .rst correctly.

Rename to .md.

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Module Findings
No security relevant content detected. Please review for security relevance and request security review as needed.

**Comment by macleodbroad-wf** [comment]
Is this really the only thing to change? Is the file actually valid markdown and not rst?

**Comment by robertharwell-wf** [comment]
Unknown until it merges.  However, this is what it looks like currently.

**Comment by macleodbroad-wf** [comment]
Sure, but I can't really +1 it if it isn't valid markdown file and we're just changing the file extension to appease the docs internal site.

**Pull request closed without merging**
