### PR TITLE
Remove newlines that are breaking ordered list rendering

### PR DESCRIPTION
**Pull request by joshhayes-sheen-wf**
Thanks to https://gist.github.com/clintel/1155906

Before:
list_fix_before

After:
list_fix_after

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
Number of Findings: 0

**Comment by ralphmarchildon-wf** [comment]
@joshhayes-sheen-wf I just noticed that the bullet list under `7. Mocks constructed with...` suffers from the same issue. Could you indent that list as well so that `If your test does ANYTHING...` continues as the expected ordered list `8.`?

**Comment by ralphmarchildon-wf** [comment]
+1

**Comment by chrislococo-wf** [comment]
Closing as included in https://github.com/Workiva/styleguide/pull/17

**Pull request closed without merging**
